#!/usr/bin/env bash
set -euo pipefail

change_shell () {
    if [ "$(echo "$SHELL" | xargs basename)" != "fish" ]; then
        sudo chsh -s "$(command -v fish)" "$USER"
        printf '\x1b[0;32mShell changed to fish.\x1b[0m\n'
    else
        printf '\x1b[0;33mShell already set to fish.\x1b[0m\n'
    fi
}

set_up_fisher () {
    curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
    fisher install laughedelic/pisces
    fisher install gazorby/fish-abbreviation-tips
}

set_up_asdf () {
    if [ ! -d "$HOME"/.asdf ]; then
        git clone https://github.com/asdf-vm/asdf.git "$HOME"/.asdf --branch v0.10.2
    fi
    mkdir -p "$HOME"/.config/fish/completions
    if [ ! -f "$HOME"/.config/fish/completions/asdf.fish ]; then
        ln -s "$HOME"/.asdf/completions/asdf.fish "$HOME"/.config/fish/completions
    fi
    . "$HOME"/.asdf/asdf.sh
    asdf update
    printf '\x1b[0;32masdf is installed. Installing tools...\x1b[0m\n'

    while IFS= read -r plugin; do
        echo "$plugin" | sed -E 's/^(.*) .*/\1/' | xargs asdf plugin add
    done < "$HOME"/.tool-versions

    cd "$HOME" || { printf '\x1b[0;31mCould not go to home directory. Exiting.\x1b[0m\n'; exit 1; }
    asdf install
    # run a second time because node-build doesn't alias its lts version the
    # first time you try to install
    asdf install
    cd - >/dev/null || { printf '\x1b[0;31mCould not return to dotfiles directory. Exiting.\x1b[0m\n'; exit 1; }

    python -m pip install --upgrade pip
    npm install -g npm
    printf '\x1b[0;32masdf tools installed.\x1b[0m\n'
}

set_up_vim () {
    if [ ! -f "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim ]; then
        sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        printf '\x1b[0;32mVim-plug has been installed.\x1b[0m\n'
    else
        printf '\x1b[0;33mVim-plug is already installed.\x1b[0m\n'
    fi

    python -m pip install pynvim
    npm install -g neovim

    nvim -e -u ~/.config/nvim/init.vim -i NONE -c "PlugInstall" -c "GoInstallBinaries" -c "qa"
    nvim -e -u ~/.config/nvim/init.vim -i NONE -c "TSInstall bash elm fish go javascript python ruby rust solidity typescript vim" -c "qa"
    echo 'Wait for CoC to install its plugins before exiting.' | nvim -R -
}

shared_setup () {
    change_shell
    set_up_fisher
    set_up_asdf
    set_up_vim
}

os_name="$(uname -s)"
echo "Setting up $os_name..."

if [ "$os_name" = "Darwin" ]; then
    if [ ! "$(xcode-select --version)" = "" ]; then
        printf '\x1b[0;32mXCode is already installed.\x1b[0m\n'
    else
        if xcode-select --install; then
            printf '\x1b[0;32mInstalled XCode.\x1b[0m\n'
        else
            printf '\x1b[0;31mFailed to install XCode. Exiting.\x1b[0m\n' && exit 1
        fi
    fi

    if sudo softwareupdate --install-rosetta --agree-to-license; then
        printf '\x1b[0;32mInstalled Rosetta.\x1b[0m\n'
    else
        printf '\x1b[0;31mFailed to install Rosetta. Exiting.\x1b[0m\n' && exit 1
    fi
    sudo softwareupdate -ir
    printf '\x1b[0;32mAttempted to install recommended updates.\x1b[0m\n'

    if [ ! -d /opt/homebrew/ ]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    brew bundle install --file Brewfile

    RCRC="$HOME"/.dotfiles/rcrc rcup -t mac
    ln -s ~/.dotfiles/karabiner/ ~/.config/karabiner

    # disable "smart" quotes
    defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

    chromedir="$(echo "$HOME"/Library/Application\ Support/Firefox/Profiles/*default-release/chrome)"
    mkdir -p chromedir
    if [ ! -f "$chromedir/userChrome.css" ]; then
        ln -s "$HOME"/.dotfiles/userChrome.css "$chromedir"/userChrome.css
        printf '\x1b[0;32mFirefox styling applied.\x1b[0m\n'
    else
        printf '\x1b[0;33mFirefox styling already exists.\x1b[0m\n'
    fi

    shared_setup
elif [ "$os_name" = "Linux" ]; then
    printf '\x1b[0;31mUpdate the install script for Linux!\x1b[0m\n'
    # TODO: install software
    # RCRC="$HOME"/.dotfiles/rcrc rcup -d ~/.dotfiles -t linux
    # TODO: settings
    # TODO: Firefox styling
    # TODO: shared setup
else
    printf '\x1b[0;31mNo installation set up for %s yet\x1b[0m\n' "$os_name"
fi

echo 'Setup complete!'
