#!/bin/bash
# don't run this file directly
# source it from your .bashrc instead, so that the directory changes affect
# the shell it's run from
# (ie. place the file your home directory and add ". ~/git-ffs" to your bashrc)

function git-ffs() {
	START=$(pwd)

	while [ ! -d .git -a ! $(pwd) = '/' ]; do
		cd ..
	done

	if [ ! $(pwd) = '/' ]; then
		URL=$(git config --get remote.origin.url)
		REPO=$(basename $(pwd))
		cd ..
		rm -rf $REPO
		BEFORE=$(ls)
		git clone $URL
		AFTER=$(ls)
		NEWFOLDER=$(diff --changed-group-format='%>' --unchanged-group-format='' <(echo "$BEFORE") <(echo "$AFTER"))
		cd $NEWFOLDER
	else
		cd $START
	fi
}

